### PR TITLE
Karsten Additions

### PR DESCRIPTION
**Pull request by ksaj**
Added circular.lisp and reflected additions in lispmath.asd and package.lisp

### CODE REVIEW

**Comment by mohindertalafuse** [comment]
A great fix to **lispmath**. Thanks for making this easily readable!

**Comment by mohindertalafuse** [comment]
The new circular.lisp file is looking good too!

**Comment by ksaj** [comment]
Before I do that, take a look at https://github.com/ksaj/lispmath/blob/master/functions-and-predicates.lisp

I made some changes you might like, but I won't push it unless you do like it.  2 things - renamed the function to 'factorial' because there are a LOT of uses of the word 'fact' in Lisp (knowledge computation, and the factors that actually make up a factorial, and of course, prime factors. Too many 'facts' out there already).

But more importantly, I made it so that you can do, for example 5!!!  (factorial 5 3) which changes the "default" factor of 1 to a factor of 3.

Since that's 2 major changes, you should look at it there first. If you don't want to change the factorial function name, but want the ability to do other factors, you can snarf the rest of it.

Incidentally, I also recoded it so it isn't doing that non-tail recursion. That could kill someone's stack if they use it in code and try to calculate the factorial of a large number. I used a loop because you can't guarantee that a particular Lisp interpreter will optimize a tail call, either.

That could be updated with +sbcl etc, but I'm more interested in simplicity than writing multiple versions of the same thing if I don't have to. ;p

**Comment by mohindertalafuse** [comment]
Interesting what you did...
I really like it!

**Comment by mohindertalafuse** [comment]
You can go ahead

**Comment by mohindertalafuse** [comment]
I'll add a _CONTRIBUTORS.md_ file

**Comment by mohindertalafuse** [comment]
But regardless, thanks for fixing the non-tail recursion; I am new to Lisp so I was not sure how to fix that.

**Comment by ksaj** [comment]
Cool. I didn't realize that changes I make after the pull request show up when you pull it. So you got the factorial stuff I was mentioning already.

Will delete my fork, and refork it if I find other stuff you might be interested in.

**Comment by mohindertalafuse** [comment]
Okay, cool

**Comment by ksaj** [comment]
A recursive version would look like this (although I don't advocate using it in a library like this, for reasons already mentioned):

(defun factorial (n &optional (fact 1))
 "Calculates factorial of a number using tail recursion."
   (if (< n 2)
     fact
     (factorial (n 1) (* acc n))))

**Comment by mohindertalafuse** [comment]
Makes sense.

Is it alright if I tweak the docstrings for your constants so that they are in order on the webpage? It is sorted alphabetically

**Comment by ksaj** [comment]
Yup go ahead.  I might need you to make another change. Testing it right now. Might not actually matter.

**Comment by mohindertalafuse** [comment]
OK

**Comment by mohindertalafuse** [comment]
I'll be alert

**Comment by mohindertalafuse** [comment]
Also τ (ταυ) is capital so it looks like T. Is this okay?

**Comment by mohindertalafuse** [comment]
Okay it's done

**Comment by mohindertalafuse** [comment]
Let me push

**Comment by ksaj** [comment]
Should it be a capital? I always see small pi, so I assume small tau is more common?  I know there could be meanings attached in full mathematical notation, but not sure if that matters.

As for the doc strings, you can change them to whatever makes things work. :)

**Comment by mohindertalafuse** [comment]
Lisp auto-capitalizes everything. It doesn't really matter.

**Comment by mohindertalafuse** [comment]
In mathematical notation, small is common.

**Comment by ksaj** [comment]
Some lisps auto-capitalize. Most people switch that off. :p

**Comment by mohindertalafuse** [comment]
However, you can't exactly easily disable auto-caps...

**Comment by mohindertalafuse** [comment]
Yep.

**Comment by mohindertalafuse** [comment]
However, the tool I use also auto-caps, and that's something I can't fix :C

**Comment by ksaj** [comment]
You can:

(setq *print-case* :lowercase)

But that's only REPL return, so it's really irrelevant except if you are doing stuff in the repl.

**Comment by ksaj** [comment]
oops.... downcase, not lowercase

**Comment by ksaj** [comment]
People typin in code don't usually ALLCAP anymore. So lowercase pi and tau are going to be a lot nicer.

**Comment by ksaj** [comment]
(setq *print-case* :lowercase) 

Dammit lol, thankfully I'm not writing an exam. 😃 

For the record, there is also :capitalize and :upcase

**Comment by mohindertalafuse** [comment]
Sorry I haven't gotten back to you...
So, if I am using a webpage writer for Lisp, would (setq \*print-case\* :downcase) work in reality? Or does it just work in the repl?

**Comment by mohindertalafuse** [comment]
Let me try...

**Comment by mohindertalafuse** [comment]
_AHA!_
It worked... had to add it to the staple.ext.lisp.
It also uncapitalized every other constant or function. But never mind that; it's how you'd write it in Lisp. 👍

**Comment by ksaj** [comment]
Literally that is only a matter of convenience for the REPL, because Lisp only sees everything as one case. You are looking at the returns, which no human ever sees unless they are using the function from the repl. And it is a personal choice, not one to force on others because of the fact that even after using print-case you can still refer to them in any case you want.

Use print-case in your ~/.sbclrc or ~/.clisprc or whatever it is for the Lisp you use. It literally makes no sense to put it actually in the functions because it changes nothing but how it is displayed on the screen in the REPL.

**Comment by ksaj** [comment]
BTW: All those italicized print-case should be \*print-case\* but I keep forgetting about markdown, heh.

**Comment by ksaj** [comment]
I don't know what you are using, but I'd toss it to the trash if it is messing with your function names.

I think you are only confusing what it shows after you DEFUN it. It is totally meaningless outside of that display.

Keep in mind that the \*print-case\* literally only refers to the P in REPL, and doesn't change the fact that it can be referenced as both capital and small tau or pi or whatever. In the same way you can do (PrInT "THIS") and it'll still show you whatever PRINT case you set it to.

Don't change the \*print-case\* in your libraries. Save that for your ~/.sbclrc or ~/clisprc or whatever it is for your lisp. You'll piss off a lot of Lispers if you change their REPL configs like that, unless that's what your library is \*supposed\* to do.

**Comment by ksaj** [comment]
Here's a link to what I consider to be the bare minimum resource you should always have by your side when programming with Lisp:

http://www.lispworks.com/documentation/HyperSpec/Front/

You probably hear about the HyperSpec in passing. It's literally as close to the Lisp Standard as you're ever going to get.

And here is probably more than you'll ever need to know about our friend \*print-case\*: 
http://www.lispworks.com/documentation/HyperSpec/Body/v_pr_cas.htm

There are cases where \*print-escape\* would be very important if you are treating it as global (and the earmuffs should tell you that it is supposed to be) 

As I mentioned though, you should never do this with setq in a library unless you have a very specific reason for it. Use it with setq in your personal configuration to make it global for your own purposes.

**Pull request merged**
